name: flutty_heroicons_example
description: Example app for flutty_heroicons
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutty_heroicons:
    path: ../
