include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    use_key_in_widget_constructors: true
    unnecessary_this: true
    always_declare_return_types: true
    prefer_final_fields: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    sized_box_for_whitespace: true
    avoid_unnecessary_containers: true
    prefer_const_declarations: true
