name: flutty_heroicons
description: "A Flutter port of HeroIcons — beautiful hand-crafted SVG icons by Tailwind, packaged for use with IconData."
version: 1.0.10
homepage: https://fluttyui.com
repository: https://github.com/miregma/flutty_heroicons
issue_tracker: https://github.com/miregma/flutty_heroicons/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: HeroIconsSolid
      fonts:
        - asset: assets/fonts/HeroIcons.ttf
    - family: HeroIconsOutline
      fonts:
        - asset: assets/fonts/HeroIconsOutline.ttf

topics:
  - icons
  - heroicons
  - flutter-ui
  - design
  - tailwind